name: Deploy Sample Project
on: push
jobs:
  test-sample-project:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Section-01/sample-project
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeSJ
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy-sample-project:
    needs: [test-sample-project]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy Project
        run: echo "Deploying project ..."
