name: Lint, Test and Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Section-01/exercise
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: ./Section-01/exercise
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ./Section-01/exercise
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying ..."
