name: Event Types and Filters
on:
  pull_request:
    types: 
      - opened
    branches:
      - 'dev-**'
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      
jobs:
  event-filter-demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Section-02/sample-project
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project ..."
